<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gerbang Depan_kolorAreaCloseBtn</name>
   <tag></tag>
   <elementGuidId>f271b36e-b773-44d9-af84-1f4900abfde4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.kolorAreaCloseBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='description4']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa948408-ad21-4299-af55-df04b27dadc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kolorAreaCloseBtn</value>
      <webElementGuid>a99ac7c1-23f1-4912-898e-02123503b9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>4e2ca99c-6cf1-4d86-a251-90b650b984fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description4&quot;)/div[@class=&quot;kolorArea&quot;]/div[@class=&quot;kolorAreaHeader&quot;]/a[@class=&quot;kolorAreaCloseBtn&quot;]</value>
      <webElementGuid>cd95f646-6c4b-41ba-b2e5-2d982bd796ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='description4']/div/div/a</value>
      <webElementGuid>b56e2933-2efb-46b7-96b8-aa978999007e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>25901a6b-2b7a-4865-9403-fa36fcb375ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Close']</value>
      <webElementGuid>39b50b67-ca71-4e47-b8d6-3c598cbd5470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
