<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TicketBooth_kolorAreaCloseBtn</name>
   <tag></tag>
   <elementGuidId>b40affab-4eb4-4a70-8029-d159b9e20c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.kolorAreaCloseBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='description6']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#description6 >> internal:attr=[title=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc288188-cbfd-4197-8236-71c81dad5c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kolorAreaCloseBtn</value>
      <webElementGuid>b73abceb-f67b-46c2-8bbc-8c4369cd5c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>74ebbc2b-b0d5-41c9-a371-bd996c40f182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description6&quot;)/div[@class=&quot;kolorArea&quot;]/div[@class=&quot;kolorAreaHeader&quot;]/a[@class=&quot;kolorAreaCloseBtn&quot;]</value>
      <webElementGuid>b4d6c2d8-ab56-426d-a180-1a9bda834b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='description6']/div/div/a</value>
      <webElementGuid>523cde29-703f-4d6a-a099-72dbf4c1ebcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>988bc4fd-5acd-4a45-bb88-3e550d973a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Close']</value>
      <webElementGuid>7c49c8da-f664-45ec-940b-a53d425ed3e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
