<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_100</name>
   <tag></tag>
   <elementGuidId>3706be19-9bd7-4c81-8ea3-8ccafe8d1b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#krpanoSWFObject > div > div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='krpanoSWFObject']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#krpanoSWFObject > div > div:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed6149bd-0b4a-4308-b18c-4f32a9ea6723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3b521f75-d903-4089-8c59-edb7b8c781ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;krpanoSWFObject&quot;)/div[1]/div[2]</value>
      <webElementGuid>436e763a-ecee-4de6-b37e-06336501526b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='krpanoSWFObject']/div/div[2]</value>
      <webElementGuid>7c062cf7-14b9-4f93-ad9b-5c4e1b432f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama saya Melody dari Team J, General Manager Theater JKT48. Saya akan memandu kalian semua.'])[1]/following::div[4]</value>
      <webElementGuid>d5d164e4-c7f5-460f-b2be-571ec4c90083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLOSE'])[1]/preceding::div[49]</value>
      <webElementGuid>60cc902e-2bad-4b2e-9a8a-c7f55727fe34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAYERS'])[1]/preceding::div[50]</value>
      <webElementGuid>31e0d92d-9d8b-4389-98d0-99e14672dd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>6f043e8e-0cb8-4c98-803c-8850cc34c2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '100%' or . = '100%')]</value>
      <webElementGuid>ee0d73ef-8788-4983-a0f5-32e6f4f5962b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
