<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>1a5d066d-8528-4ce2-aa0b-1413d4e349c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fanclubModal04 > div.modal-dialog.modal-lg.modal-dialog-centered > div.modal-content > div.modal-header > button.close > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '×' or . = '×')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fanclubModal04']/div/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>542fcb62-71cb-48d8-bd1f-7856a3dd5f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ca83d6d-1bee-47d5-bb7c-3ed7038c88af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2279a203-d553-4997-8c02-686717230c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fanclubModal04&quot;)/div[@class=&quot;modal-dialog modal-lg modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/button[@class=&quot;close&quot;]/span[1]</value>
      <webElementGuid>df8fd98d-ef82-4342-bb17-771c08ca5a3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal04']/div/div/div/button/span</value>
      <webElementGuid>bcab956f-61fc-41d1-a7cf-c02942fdd842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event spesial OFC, Online dan Offline!'])[1]/following::span[1]</value>
      <webElementGuid>ff65e63e-a570-4282-879c-fb96b1853076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioritas Tiket Untuk Event, JKT48 Theater, dan Konser'])[1]/following::span[2]</value>
      <webElementGuid>e02a2eef-0f26-4f52-97a7-2a5665a5765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Eksklusif Ucapan Ulang Tahun!'])[1]/preceding::span[1]</value>
      <webElementGuid>b2592057-002d-4bde-9341-8c941f666d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUMINA: Exclusive Cinematic Vlog'])[1]/preceding::span[2]</value>
      <webElementGuid>50d07773-f484-4896-aefa-390b45787797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/button/span</value>
      <webElementGuid>cc0228cd-ffbd-4bed-a4de-7099d8319edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>c8f0c87a-14de-43ab-9877-730329070a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal06']/div/div/div/button/span</value>
      <webElementGuid>54328853-70bc-4eae-9e45-70deeec08c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUMINA: Exclusive Cinematic Vlog'])[1]/following::span[1]</value>
      <webElementGuid>0e32511c-1cb2-4662-9a9d-36bbb6b73a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Eksklusif Ucapan Ulang Tahun!'])[1]/following::span[2]</value>
      <webElementGuid>09558da2-9af6-4210-95b6-e6531b32edf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photoshoot Behind The Scene'])[1]/preceding::span[1]</value>
      <webElementGuid>c2660e23-6d38-4900-985c-bbfd9992102a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discord Stage Channel'])[1]/preceding::span[2]</value>
      <webElementGuid>5c46e138-3903-435f-bdfd-5c9c578cc579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/button/span</value>
      <webElementGuid>e9962b22-d7f0-49f7-b962-bd6ab3b62bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal07']/div/div/div/button/span</value>
      <webElementGuid>35e656b6-c81d-437c-8cd5-64b9fa01817b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photoshoot Behind The Scene'])[1]/following::span[1]</value>
      <webElementGuid>ec006ce0-c6de-4867-9075-ceda7d1832d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUMINA: Exclusive Cinematic Vlog'])[1]/following::span[2]</value>
      <webElementGuid>2f713076-90d2-45b4-a1d8-e70cd4d274df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discord Stage Channel'])[1]/preceding::span[1]</value>
      <webElementGuid>3c551b8d-96ff-480b-be3e-9cdcae4da0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN UP!'])[1]/preceding::span[1]</value>
      <webElementGuid>997933ce-c0da-4a20-8305-602ac1d71341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/button/span</value>
      <webElementGuid>aecfab3a-0b30-42b0-80c0-da4bb19f4ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal03']/div/div/div/button/span</value>
      <webElementGuid>ccc4cdca-be56-4b07-a7a2-3813c7f0f906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioritas Tiket Untuk Event, JKT48 Theater, dan Konser'])[1]/following::span[1]</value>
      <webElementGuid>c92012a0-d610-4ecd-b1a1-6eea6246776b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Anggota OFC + Badge Spesial.'])[1]/following::span[2]</value>
      <webElementGuid>998113bc-78b1-4380-987a-6f67542a0d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event spesial OFC, Online dan Offline!'])[1]/preceding::span[1]</value>
      <webElementGuid>ca6e724a-4a38-4422-850b-54cb89f77568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Eksklusif Ucapan Ulang Tahun!'])[1]/preceding::span[2]</value>
      <webElementGuid>dc163db0-1f7b-41ae-91c9-ffb758583f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/button/span</value>
      <webElementGuid>a4d3fbd0-429c-459d-a383-2079ba0d7fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal05']/div/div/div/button/span</value>
      <webElementGuid>306d016b-1d5e-498b-8f44-a989a567f702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video Eksklusif Ucapan Ulang Tahun!'])[1]/following::span[1]</value>
      <webElementGuid>ca9d557f-44b7-4f6b-88aa-2276bf8c428e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event spesial OFC, Online dan Offline!'])[1]/following::span[2]</value>
      <webElementGuid>12a88558-c1a1-4996-af19-489ca53c71e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUMINA: Exclusive Cinematic Vlog'])[1]/preceding::span[1]</value>
      <webElementGuid>7aa79dfe-aea6-4875-953f-92fff765e444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photoshoot Behind The Scene'])[1]/preceding::span[2]</value>
      <webElementGuid>0acadfa9-2ba4-4eef-9f99-4758bdc809d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/button/span</value>
      <webElementGuid>5708f4f0-30f4-42a6-98bf-243a34c1638e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal02']/div/div/div/button/span</value>
      <webElementGuid>83f10fd5-32ef-4b57-b28b-4b41bca34643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Anggota OFC + Badge Spesial.'])[1]/following::span[1]</value>
      <webElementGuid>5b4cdcd8-6ab6-4d59-834c-c0b1bff00830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENEFITS'])[1]/following::span[2]</value>
      <webElementGuid>9f94f0b2-a890-4fbb-96a9-8057b054ae57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioritas Tiket Untuk Event, JKT48 Theater, dan Konser'])[1]/preceding::span[1]</value>
      <webElementGuid>c03962aa-15ed-4d11-9a41-ebd937e61b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event spesial OFC, Online dan Offline!'])[1]/preceding::span[2]</value>
      <webElementGuid>23ac74b1-258b-4183-97ac-39842f2e5023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/button/span</value>
      <webElementGuid>53fc0a8e-d625-4007-a761-28873d4b95f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fanclubModal01']/div/div/div/button/span</value>
      <webElementGuid>ee898492-2551-4a18-9a15-65c73649c7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENEFITS'])[1]/following::span[1]</value>
      <webElementGuid>6f8a79f3-a689-4bba-a278-a10120e240d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OFFICIAL FAN CLUB MEMBERSHIP RENEWAL 2024'])[1]/following::span[1]</value>
      <webElementGuid>5ec541bf-8231-4554-877d-9c8a0580f0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Anggota OFC + Badge Spesial.'])[1]/preceding::span[1]</value>
      <webElementGuid>652ffbe8-9744-4f0e-b5c8-5bb97bde9a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioritas Tiket Untuk Event, JKT48 Theater, dan Konser'])[1]/preceding::span[2]</value>
      <webElementGuid>3768fc90-65d4-459b-9ce1-d81084119bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>e730a00c-c75b-4f1e-968e-b444b70fcd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>a243ebed-5283-49ee-871a-0d007209638a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
