<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FANCLUB</name>
   <tag></tag>
   <elementGuidId>f84ad878-0b37-43b3-8b2f-0126264ee355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'FANCLUB')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:role=link[name=&quot;FANCLUB&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3b10cea-58b7-44f0-bccc-b14116984cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fanclub?lang=id</value>
      <webElementGuid>152fa2b6-3edc-41ed-b87c-bf44173b5c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FANCLUB</value>
      <webElementGuid>0eb44de5-9347-43ca-9a80-c60bb68f472a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/nav[@class=&quot;nav-global&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav-global__list d-flex align-items-center justify-content-between&quot;]/li[@class=&quot;nav-global__item&quot;]/a[1]</value>
      <webElementGuid>de5e863c-fc3b-4cb1-896d-1a4fb295bd1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FANCLUB')]</value>
      <webElementGuid>c4c1ee58-8b8d-4ffd-9b21-4a0b12f3e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JKT48 Shop at Shopee'])[1]/following::a[1]</value>
      <webElementGuid>abcd4513-f1e5-4a92-aab5-858c08e8ad7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JKT48 Shop at Tokopedia'])[1]/following::a[2]</value>
      <webElementGuid>d0157e69-09b3-480b-b75f-f23530a4a4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>fd735d96-0fd6-409d-82d4-cf7117cdbda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Page'])[3]/preceding::a[2]</value>
      <webElementGuid>b4fc4ea3-b12f-4f4f-b401-90a2b86b54a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FANCLUB']/parent::*</value>
      <webElementGuid>75838d20-583f-4528-baee-72594aa18d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fanclub?lang=id')]</value>
      <webElementGuid>71bed86a-e23d-43e5-be4c-23b2447a6f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>c887940c-44be-47cd-b4e1-90bdb591f6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fanclub?lang=id' and (text() = 'FANCLUB' or . = 'FANCLUB')]</value>
      <webElementGuid>4946e3b3-42a5-4e20-8038-23ad2301e026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
