<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MEMBER</name>
   <tag></tag>
   <elementGuidId>58f733b9-6492-41eb-a6a1-5a16b3676abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'MEMBER')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:role=link[name=&quot;MEMBER&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d77565e-aa03-46b8-9a5a-6c9a20ffad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/member/list?lang=id</value>
      <webElementGuid>4618c8af-b93c-442a-a8c6-1adf862d8a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MEMBER</value>
      <webElementGuid>2c8bde8b-f9e5-451d-b6c8-4bdfef12dd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/nav[@class=&quot;nav-global&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav-global__list d-flex align-items-center justify-content-between&quot;]/li[@class=&quot;nav-global__item&quot;]/a[1]</value>
      <webElementGuid>de351fae-d010-4b53-ad36-079efb625e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MEMBER')]</value>
      <webElementGuid>1866e187-c9d7-4e8b-b750-1b0ae74dafbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULE'])[1]/following::a[1]</value>
      <webElementGuid>17d15b6b-80cb-49a2-8ee4-69d8e8376d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEWS'])[1]/following::a[2]</value>
      <webElementGuid>c8ae6f83-e5b7-445e-9219-14d6a594434a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa Itu Teater JKT48'])[1]/preceding::a[1]</value>
      <webElementGuid>3f30b1a2-0b2a-4c07-8062-1aa1f43e51d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEMBER']/parent::*</value>
      <webElementGuid>badd322a-0a06-4ad0-b119-2e9f4d39d536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/member/list?lang=id')]</value>
      <webElementGuid>09fbc133-1aab-4f08-b14e-de809ff4fd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>2e7d2a28-4fbe-4b68-84f2-e568d17f67a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/member/list?lang=id' and (text() = 'MEMBER' or . = 'MEMBER')]</value>
      <webElementGuid>bcc29f2b-15e0-4f80-bf41-1ab58d50b933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
