<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NEWS</name>
   <tag></tag>
   <elementGuidId>105f202c-24f4-4e0a-b8de-3124113958a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.nav-global__item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'NEWS')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:role=link[name=&quot;NEWS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d2fa27f-80b3-4f46-87cf-a77e2a7bbc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news/list?lang=id</value>
      <webElementGuid>547a72b2-8c2b-4768-b530-cb28c861cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEWS</value>
      <webElementGuid>3fc5a8e8-5f94-40dd-b2bb-743f621667d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/nav[@class=&quot;nav-global&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav-global__list d-flex align-items-center justify-content-between&quot;]/li[@class=&quot;nav-global__item&quot;]/a[1]</value>
      <webElementGuid>922ca918-b08d-4bd5-80ac-3962bde87a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NEWS')]</value>
      <webElementGuid>737eb394-861f-42db-9626-b7b8e5871c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/following::a[1]</value>
      <webElementGuid>8aac89ef-7c0b-43a8-96c5-e9cde46071c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Page'])[2]/following::a[2]</value>
      <webElementGuid>f3057ff2-1c6b-4cc7-bcff-7ecfa75faa93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCHEDULE'])[1]/preceding::a[1]</value>
      <webElementGuid>334ea559-ce43-43f3-8b65-51661778fe4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEMBER'])[1]/preceding::a[2]</value>
      <webElementGuid>a3850150-8396-491c-9994-e60771c910f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NEWS']/parent::*</value>
      <webElementGuid>6faf0eab-5085-4721-8f75-7c1ffbd6e404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/news/list?lang=id')]</value>
      <webElementGuid>9792334f-4988-468a-9a70-49b267514020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>a3fcc1a9-85b1-4fd2-b718-bd761a0b1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news/list?lang=id' and (text() = 'NEWS' or . = 'NEWS')]</value>
      <webElementGuid>ce8038be-7b92-4e23-844a-3dadb036ef9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
