<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SCHEDULE</name>
   <tag></tag>
   <elementGuidId>b0305a06-0b6d-4b9e-ac08-4964cf274134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SCHEDULE')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:role=link[name=&quot;SCHEDULE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3998fdd9-c94c-4c75-91c3-9a1032739832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/calendar/list?lang=id</value>
      <webElementGuid>941527bf-9201-4206-aad0-29ee1cb62166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCHEDULE</value>
      <webElementGuid>d333b972-620b-41aa-b323-eb09977f2b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/nav[@class=&quot;nav-global&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;nav-global__list d-flex align-items-center justify-content-between&quot;]/li[@class=&quot;nav-global__item&quot;]/a[1]</value>
      <webElementGuid>14d539cd-8283-43b5-944a-194c159191b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SCHEDULE')]</value>
      <webElementGuid>7f981b5e-dc82-4ca9-b3e6-357346b68d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEWS'])[1]/following::a[1]</value>
      <webElementGuid>6d873d6c-2dca-45f7-92fe-155d74c37f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/following::a[2]</value>
      <webElementGuid>80300fe4-e269-4e43-93e8-c0401926c975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEMBER'])[1]/preceding::a[1]</value>
      <webElementGuid>ae997584-05b4-43f3-8020-13884d06efa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SCHEDULE']/parent::*</value>
      <webElementGuid>545bf73a-1b9b-4861-9a06-45eb28049f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/calendar/list?lang=id')]</value>
      <webElementGuid>162102f4-750a-45bb-bb4f-2b59a01de0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>fd2a3f35-d150-4076-a5d4-8a95aad834fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/calendar/list?lang=id' and (text() = 'SCHEDULE' or . = 'SCHEDULE')]</value>
      <webElementGuid>8ad5a74d-7b15-4282-9653-fa9a4c291d2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
